version: '3.8'

services:
  sourcefuse:
    image: sourcefuse
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5555:80"
    networks:
      - product-network

networks:
    product-network:
        driver: bridge